name: flutter_stacked_starter
description: Stater app for creating scalable mobile apps with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Stacked State Management
  stacked: ^3.2.5
  stacked_services: ^1.0.2
  stacked_generator: ^1.3.2

  # Data Models
  freezed_annotation:
  json_annotation: ^4.0.1

  # UI
  cupertino_icons: ^1.0.2

  # Network
  dio: ^5.2.1+1
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Code Generation
  build_runner:

  # Data Models
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
